apiVersion: v1
kind: ServiceAccount
metadata:
  name: xspace-agent-sa
  namespace: xspace-agent
  labels:
    app: xspace-agent
  annotations:
    # Workload Identity: maps this KSA to the GCP SA created by Terraform.
    # Replace PROJECT_ID with the actual GCP project ID.
    iam.gke.io/gcp-service-account: xspace-agent-sa@PROJECT_ID.iam.gserviceaccount.com
